# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'auramirea'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectKey=auramirea_java-on-aks

- task: Maven@3
  inputs:
    mavenPomFile: 'account-service/pom.xml'
    goals: 'verify sonar:sonar'
    publishJUnitResults: true
    testResultsFiles: 'account-service/**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
  
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'